/** Opštini / municipalities commonly used across MK registries — filter UI + register wizard. */
export const MK_MUNICIPALITIES: string[] = [
  'Aračinovo',
  'Berovo',
  'Bitola',
  'Bogdanci',
  'Bogovinje',
  'Bosilovo',
  'Brvenica',
  'Butel',
  'Čair',
  'Čaška',
  'Centar',
  'Centar Župa',
  'Češinovo-Obleševo',
  'Čučer-Sandevo',
  'Debar',
  'Debarca',
  'Delčevo',
  'Demir Hisar',
  'Demir Kapija',
  'Dolneni',
  'Drugovo',
  'Gazi Baba',
  'Gevgelija',
  'Gjorče Petrov',
  'Gostivar',
  'Gradsko',
  'Ilinden',
  'Jegunovce',
  'Karbinci',
  'Karpoš',
  'Kavadarci',
  'Kičevo',
  'Kočani',
  'Konče',
  'Kratovo',
  'Kriva Palanka',
  'Krivogaštani',
  'Kruševo',
  'Kumanovo',
  'Lipkovo',
  'Lozovo',
  'Makedonska Kamenica',
  'Makedonski Brod',
  'Mavrovo i Rostuše',
  'Mogila',
  'Negotino',
  'Novaci',
  'Novo Selo',
  'Ohrid',
  'Oslomej',
  'Pehčevo',
  'Petrovec',
  'Plasnica',
  'Prilep',
  'Probištip',
  'Radoviš',
  'Rankovce',
  'Resen',
  'Rosoman',
  'Saraj',
  'Sopište',
  'Star Dojran',
  'Star Nagoričane',
  'Štip',
  'Struga',
  'Strumica',
  'Studeničani',
  'Šuto Orizari',
  'Sveti Nikole',
  'Tearce',
  'Tetovo',
  'Valandovo',
  'Vasilevo',
  'Veles',
  'Vevčani',
  'Vinica',
  'Vrapčište',
  'Zajas',
  'Zelenikovo',
  'Želino',
  'Zrnovci',
];
